[project]
name = "learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.38.0",
    "google-generativeai",
    "mcp[cli]>=1.15.0",
    "pip>=25.2",
    "python-pptx>=1.0.2",
    "requests>=2.32.5",
]
